# -*- coding: utf-8 -*-
"""AddNumbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCAndjoJh1s6sb1RAnqgnUeYyWo6ky7k
"""

a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
c = a + b

print("The sum of the two numbers is:" , c)