# -*- coding: utf-8 -*-
"""AddNumbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCAndjoJh1s6sb1RAnqgnUeYyWo6ky7k
"""

#assign two varibles for user to input two numbers
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
#create the calculation for the numbers to be added together
c = a + b
#print out the results
print("The sum of the two numbers is:" , c)